config/routes.rb
Rails.application.routes.draw do
  
  devise_for :registers
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_register!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
 <p class="navbar-text float-right">
      <% if register_signed_in? %>
        <h5> Welcome to HR-Interview-Management <strong><%= current_register.email %></strong>. </h5>
        <%= button_to "Edit profile", edit_register_registration_path, class: "navbar-link" %> <br>
        <%= button_to "Logout", destroy_register_session_path, method: :delete, class: "navbar-link"  %>
      <% else %>
        <%= button_to "Sign up", new_register_registration_path, class: "navbar-link"  %> 
        <%= button_to "Login", new_register_session_path, class: "navbar-link"  %>
      <% end %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <h1> 
  <h1>HR-Interview-Management</h1>
   <%= yield %>

  <div class = "mb-5">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
  </div>
    
   

    <%# <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/ideas">Ideas</a>
        </li>
        ...
    </ul> %>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>